# Auto-generated by install_dev_assistant.py
"""DevAssistant module for Actifix.

This module exposes a simple API endpoint that proxies chat requests
to a locally running Ollama model.  The assistant is primed with a
summary of the Actifix architecture (see the PRIMER constant below) so
that it can generate context-aware responses for developers working
within this repository.  To use this module, ensure that your
Ollama server is running at http://localhost:11434 and that the model
specified in MODULE_DEFAULTS['model'] is pulled locally (e.g.
`ollama pull qwen2.5-coder:7b-instruct`).

The blueprint registers two routes under the prefix ``/modules/dev-assistant``:
  • ``/health`` returns the module health status via ModuleBase.  It
    uses the standard ModuleBase health implementation.
  • ``/chat`` accepts a JSON payload with a ``prompt`` field and
    returns the assistant's response in a JSON body.  Errors are
    logged via ModuleBase and a 500 response is returned on failure.
"""

from __future__ import annotations

import requests
from typing import Optional, Union
from pathlib import Path

from actifix.modules.base import ModuleBase
from actifix.modules.config import get_module_config
from actifix.raise_af import TicketPriority

# Defaults and metadata for the DevAssistant module
MODULE_DEFAULTS = {
    "model": "qwen2.5-coder:7b-instruct",
}

MODULE_METADATA = {
    "name": "modules.dev_assistant",
    "version": "1.0.0",
    "description": "Local AI coding assistant using Ollama with Actifix primer.",
    "capabilities": {"ai": True},
    "data_access": {"state_dir": False},
    "network": {"external_requests": False},
    "permissions": ["logging"],
}

MODULE_DEPENDENCIES = [
    "runtime.state",
    "infra.logging",
    "core.raise_af",
    "runtime.api",
]

# Long primer text passed to the model on every request.  See
# install_dev_assistant.py for details.
PRIMER = "You are DevAssistant, an expert software engineer assisting with the Actifix project. Actifix is a modular error tracking and self‑healing framework. The Python backend lives under the 'src/actifix' directory. Key components include:\n- 'bootstrap.py': initializes the framework and sets up runtime state.\n- 'config.py': defines ActifixConfig; defaults control AI integration, including the AI provider and model.\n- 'raise_af.py': captures errors and persists tickets. Use the `record_error()` function to record any new issues; never silently create files outside of the ticketing system.\n- 'do_af.py': processes tickets, dispatches them to AI providers and marks them complete when fixes succeed.\n- 'ai_client.py': provides multi‑provider AI integration with fallback logic.  When working inside a module you generally do not need to call this directly; modules should proxy to their own local provider if appropriate.\n- 'persistence/': implements SQLite persistence via the ticket and event repositories. The database file lives under 'data/actifix.db'.\n- 'modules/': contains additional optional modules which register Flask blueprints on the runtime API. Each module defines MODULE_DEFAULTS, MODULE_METADATA, MODULE_DEPENDENCIES and implements a `create_blueprint` function returning a Flask Blueprint.\nThe React front‑end is located in 'actifix-frontend' and consumes the REST API exposed by the backend. Any UI changes should be placed in that directory. Always adhere to existing code patterns: use Python 3.10 syntax, respect the project layout, record errors via `record_error()`, write files with `atomic_write()`, and keep persistence confined to the ticket repository. Use comments sparingly and focus on clear, readable code."

def _module_helper(project_root: Optional[Union[str, Path]] = None) -> ModuleBase:
    """Return a ModuleBase helper configured for this module."""
    return ModuleBase(
        module_key="dev_assistant",
        defaults=MODULE_DEFAULTS,
        metadata=MODULE_METADATA,
        project_root=project_root,
    )


def _resolve_model(
    helper: ModuleBase,
    project_root: Optional[Union[str, Path]],
    override: Optional[str],
) -> str:
    """Return the Ollama model name, using overrides or module config."""
    if override:
        return override
    module_config = get_module_config(helper.module_key, helper.module_defaults, project_root=project_root)
    return str(module_config.get("model") or MODULE_DEFAULTS["model"])

def create_blueprint(
    project_root: Optional[Union[str, Path]] = None,
    model: Optional[str] = None,
    url_prefix: Optional[str] = "/modules/dev-assistant",
) -> "Blueprint":
    """Create and return the Flask blueprint for the DevAssistant module.

    The returned blueprint will have ``/health`` and ``/chat`` routes.

    Args:
        project_root: Optional override for the project root.
        model: Optional override for the Ollama model name.
        url_prefix: URL prefix for the blueprint.  Defaults to
            ``/modules/dev-assistant``.

    Returns:
        flask.Blueprint: The configured blueprint.
    """
    helper = _module_helper(project_root)
    try:
        from flask import Blueprint, request, jsonify

        blueprint = Blueprint("dev_assistant", __name__, url_prefix=url_prefix)
        resolved_model = _resolve_model(helper, project_root, model)

        @blueprint.route("/health")
        def health():
            return helper.health_response()

        @blueprint.route("/chat", methods=["POST"])
        def chat():
            # Extract the prompt from the incoming JSON body
            data = request.get_json(silent=True) or {}
            prompt = data.get("prompt") or data.get("message") or ""
            if not isinstance(prompt, str) or not prompt.strip():
                return jsonify({"error": "Missing or empty prompt"}), 400
            try:
                payload = {
                    "model": resolved_model,
                    "messages": [
                        {"role": "system", "content": PRIMER},
                        {"role": "user", "content": prompt.strip()},
                    ],
                }
                response = requests.post(
                    "http://localhost:11434/api/chat",
                    json=payload,
                    timeout=60,
                )
                response.raise_for_status()
                result = response.json()
                # Ollama returns either {"message": {"content": ...}} or {"response": ...}
                answer = (
                    (result.get("message") or {}).get("content")
                    or result.get("response")
                    or ""
                )
                return jsonify({"assistant": answer})
            except Exception as exc:
                helper.record_module_error(
                    message=f"DevAssistant failed: {exc}",
                    source="modules/dev_assistant",
                    error_type=type(exc).__name__,
                    priority=TicketPriority.P2,
                )
                return jsonify({"error": str(exc)}), 500

        return blueprint
    except Exception as exc:
        helper.record_module_error(
            message=f"Failed to create DevAssistant blueprint: {exc}",
            source="modules/dev_assistant",
            error_type=type(exc).__name__,
            priority=TicketPriority.P1,
        )
        raise

def run_gui(*args, **kwargs) -> None:
    """This module does not provide a GUI."""
    raise NotImplementedError("DevAssistant does not implement a graphical interface.")
